// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employeedata_message.proto

package com.employeedata.service.app.protobuf;

public final class EmployeeDataProto {
  private EmployeeDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protobuf.eFileType}
   */
  public enum eFileType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CSV = 0;</code>
     */
    CSV(0),
    /**
     * <code>XML = 1;</code>
     */
    XML(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CSV = 0;</code>
     */
    public static final int CSV_VALUE = 0;
    /**
     * <code>XML = 1;</code>
     */
    public static final int XML_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static eFileType valueOf(int value) {
      return forNumber(value);
    }

    public static eFileType forNumber(int value) {
      switch (value) {
        case 0: return CSV;
        case 1: return XML;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<eFileType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        eFileType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<eFileType>() {
            public eFileType findValueByNumber(int number) {
              return eFileType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.employeedata.service.app.protobuf.EmployeeDataProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final eFileType[] VALUES = values();

    public static eFileType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private eFileType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.eFileType)
  }

  public interface EmployeeDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.EmployeeDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string dob = 2;</code>
     */
    java.lang.String getDob();
    /**
     * <code>optional string dob = 2;</code>
     */
    com.google.protobuf.ByteString
        getDobBytes();

    /**
     * <code>optional double salary = 3;</code>
     */
    double getSalary();

    /**
     * <code>optional uint32 age = 4;</code>
     */
    int getAge();

    /**
     * <code>optional .protobuf.eFileType fileType = 5;</code>
     */
    int getFileTypeValue();
    /**
     * <code>optional .protobuf.eFileType fileType = 5;</code>
     */
    com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType getFileType();
  }
  /**
   * Protobuf type {@code protobuf.EmployeeDataMessage}
   */
  public  static final class EmployeeDataMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.EmployeeDataMessage)
      EmployeeDataMessageOrBuilder {
    // Use EmployeeDataMessage.newBuilder() to construct.
    private EmployeeDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmployeeDataMessage() {
      name_ = "";
      dob_ = "";
      salary_ = 0D;
      age_ = 0;
      fileType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EmployeeDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dob_ = s;
              break;
            }
            case 25: {

              salary_ = input.readDouble();
              break;
            }
            case 32: {

              age_ = input.readUInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              fileType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_EmployeeDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_EmployeeDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage.class, com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOB_FIELD_NUMBER = 2;
    private volatile java.lang.Object dob_;
    /**
     * <code>optional string dob = 2;</code>
     */
    public java.lang.String getDob() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dob_ = s;
        return s;
      }
    }
    /**
     * <code>optional string dob = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDobBytes() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALARY_FIELD_NUMBER = 3;
    private double salary_;
    /**
     * <code>optional double salary = 3;</code>
     */
    public double getSalary() {
      return salary_;
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private int age_;
    /**
     * <code>optional uint32 age = 4;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int FILETYPE_FIELD_NUMBER = 5;
    private int fileType_;
    /**
     * <code>optional .protobuf.eFileType fileType = 5;</code>
     */
    public int getFileTypeValue() {
      return fileType_;
    }
    /**
     * <code>optional .protobuf.eFileType fileType = 5;</code>
     */
    public com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType getFileType() {
      com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType result = com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.valueOf(fileType_);
      return result == null ? com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getDobBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dob_);
      }
      if (salary_ != 0D) {
        output.writeDouble(3, salary_);
      }
      if (age_ != 0) {
        output.writeUInt32(4, age_);
      }
      if (fileType_ != com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.CSV.getNumber()) {
        output.writeEnum(5, fileType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getDobBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dob_);
      }
      if (salary_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, salary_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, age_);
      }
      if (fileType_ != com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.CSV.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, fileType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage)) {
        return super.equals(obj);
      }
      com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage other = (com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getDob()
          .equals(other.getDob());
      result = result && (
          java.lang.Double.doubleToLongBits(getSalary())
          == java.lang.Double.doubleToLongBits(
              other.getSalary()));
      result = result && (getAge()
          == other.getAge());
      result = result && fileType_ == other.fileType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOB_FIELD_NUMBER;
      hash = (53 * hash) + getDob().hashCode();
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSalary()));
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + fileType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.EmployeeDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.EmployeeDataMessage)
        com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_EmployeeDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_EmployeeDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage.class, com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage.Builder.class);
      }

      // Construct using com.employeedata.endpoint.app.protobuf.EmployeeDataProto.EmployeeDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        dob_ = "";

        salary_ = 0D;

        age_ = 0;

        fileType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_EmployeeDataMessage_descriptor;
      }

      public com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage getDefaultInstanceForType() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage.getDefaultInstance();
      }

      public com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage build() {
        com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage buildPartial() {
        com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage result = new com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage(this);
        result.name_ = name_;
        result.dob_ = dob_;
        result.salary_ = salary_;
        result.age_ = age_;
        result.fileType_ = fileType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage) {
          return mergeFrom((com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage other) {
        if (other == com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDob().isEmpty()) {
          dob_ = other.dob_;
          onChanged();
        }
        if (other.getSalary() != 0D) {
          setSalary(other.getSalary());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.fileType_ != 0) {
          setFileTypeValue(other.getFileTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dob_ = "";
      /**
       * <code>optional string dob = 2;</code>
       */
      public java.lang.String getDob() {
        java.lang.Object ref = dob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dob_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dob = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDobBytes() {
        java.lang.Object ref = dob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dob = 2;</code>
       */
      public Builder setDob(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dob = 2;</code>
       */
      public Builder clearDob() {
        
        dob_ = getDefaultInstance().getDob();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dob = 2;</code>
       */
      public Builder setDobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dob_ = value;
        onChanged();
        return this;
      }

      private double salary_ ;
      /**
       * <code>optional double salary = 3;</code>
       */
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>optional double salary = 3;</code>
       */
      public Builder setSalary(double value) {
        
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double salary = 3;</code>
       */
      public Builder clearSalary() {
        
        salary_ = 0D;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional uint32 age = 4;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional uint32 age = 4;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 age = 4;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int fileType_ = 0;
      /**
       * <code>optional .protobuf.eFileType fileType = 5;</code>
       */
      public int getFileTypeValue() {
        return fileType_;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 5;</code>
       */
      public Builder setFileTypeValue(int value) {
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 5;</code>
       */
      public com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType getFileType() {
        com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType result = com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.valueOf(fileType_);
        return result == null ? com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 5;</code>
       */
      public Builder setFileType(com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fileType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 5;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.EmployeeDataMessage)
    }

    // @@protoc_insertion_point(class_scope:protobuf.EmployeeDataMessage)
    private static final com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage();
    }

    public static com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmployeeDataMessage>
        PARSER = new com.google.protobuf.AbstractParser<EmployeeDataMessage>() {
      public EmployeeDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EmployeeDataMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmployeeDataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmployeeDataMessage> getParserForType() {
      return PARSER;
    }

    public com.employeedata.service.app.protobuf.EmployeeDataProto.EmployeeDataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdatedEmployeeDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.UpdatedEmployeeDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string updateName = 1;</code>
     */
    java.lang.String getUpdateName();
    /**
     * <code>optional string updateName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUpdateNameBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string dob = 3;</code>
     */
    java.lang.String getDob();
    /**
     * <code>optional string dob = 3;</code>
     */
    com.google.protobuf.ByteString
        getDobBytes();

    /**
     * <code>optional double salary = 4;</code>
     */
    double getSalary();

    /**
     * <code>optional uint32 age = 5;</code>
     */
    int getAge();

    /**
     * <code>optional .protobuf.eFileType fileType = 6;</code>
     */
    int getFileTypeValue();
    /**
     * <code>optional .protobuf.eFileType fileType = 6;</code>
     */
    com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType getFileType();
  }
  /**
   * Protobuf type {@code protobuf.UpdatedEmployeeDataMessage}
   */
  public  static final class UpdatedEmployeeDataMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.UpdatedEmployeeDataMessage)
      UpdatedEmployeeDataMessageOrBuilder {
    // Use UpdatedEmployeeDataMessage.newBuilder() to construct.
    private UpdatedEmployeeDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdatedEmployeeDataMessage() {
      updateName_ = "";
      name_ = "";
      dob_ = "";
      salary_ = 0D;
      age_ = 0;
      fileType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdatedEmployeeDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              updateName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              dob_ = s;
              break;
            }
            case 33: {

              salary_ = input.readDouble();
              break;
            }
            case 40: {

              age_ = input.readUInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              fileType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_UpdatedEmployeeDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_UpdatedEmployeeDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage.class, com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage.Builder.class);
    }

    public static final int UPDATENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object updateName_;
    /**
     * <code>optional string updateName = 1;</code>
     */
    public java.lang.String getUpdateName() {
      java.lang.Object ref = updateName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string updateName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateNameBytes() {
      java.lang.Object ref = updateName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOB_FIELD_NUMBER = 3;
    private volatile java.lang.Object dob_;
    /**
     * <code>optional string dob = 3;</code>
     */
    public java.lang.String getDob() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dob_ = s;
        return s;
      }
    }
    /**
     * <code>optional string dob = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDobBytes() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_;
    /**
     * <code>optional double salary = 4;</code>
     */
    public double getSalary() {
      return salary_;
    }

    public static final int AGE_FIELD_NUMBER = 5;
    private int age_;
    /**
     * <code>optional uint32 age = 5;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int FILETYPE_FIELD_NUMBER = 6;
    private int fileType_;
    /**
     * <code>optional .protobuf.eFileType fileType = 6;</code>
     */
    public int getFileTypeValue() {
      return fileType_;
    }
    /**
     * <code>optional .protobuf.eFileType fileType = 6;</code>
     */
    public com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType getFileType() {
      com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType result = com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.valueOf(fileType_);
      return result == null ? com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUpdateNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, updateName_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getDobBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dob_);
      }
      if (salary_ != 0D) {
        output.writeDouble(4, salary_);
      }
      if (age_ != 0) {
        output.writeUInt32(5, age_);
      }
      if (fileType_ != com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.CSV.getNumber()) {
        output.writeEnum(6, fileType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUpdateNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, updateName_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getDobBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dob_);
      }
      if (salary_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, age_);
      }
      if (fileType_ != com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.CSV.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, fileType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage)) {
        return super.equals(obj);
      }
      com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage other = (com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage) obj;

      boolean result = true;
      result = result && getUpdateName()
          .equals(other.getUpdateName());
      result = result && getName()
          .equals(other.getName());
      result = result && getDob()
          .equals(other.getDob());
      result = result && (
          java.lang.Double.doubleToLongBits(getSalary())
          == java.lang.Double.doubleToLongBits(
              other.getSalary()));
      result = result && (getAge()
          == other.getAge());
      result = result && fileType_ == other.fileType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UPDATENAME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateName().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOB_FIELD_NUMBER;
      hash = (53 * hash) + getDob().hashCode();
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSalary()));
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + fileType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.UpdatedEmployeeDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.UpdatedEmployeeDataMessage)
        com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_UpdatedEmployeeDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_UpdatedEmployeeDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage.class, com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage.Builder.class);
      }

      // Construct using com.employeedata.endpoint.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        updateName_ = "";

        name_ = "";

        dob_ = "";

        salary_ = 0D;

        age_ = 0;

        fileType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.internal_static_protobuf_UpdatedEmployeeDataMessage_descriptor;
      }

      public com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage getDefaultInstanceForType() {
        return com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage.getDefaultInstance();
      }

      public com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage build() {
        com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage buildPartial() {
        com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage result = new com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage(this);
        result.updateName_ = updateName_;
        result.name_ = name_;
        result.dob_ = dob_;
        result.salary_ = salary_;
        result.age_ = age_;
        result.fileType_ = fileType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage) {
          return mergeFrom((com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage other) {
        if (other == com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage.getDefaultInstance()) return this;
        if (!other.getUpdateName().isEmpty()) {
          updateName_ = other.updateName_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDob().isEmpty()) {
          dob_ = other.dob_;
          onChanged();
        }
        if (other.getSalary() != 0D) {
          setSalary(other.getSalary());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.fileType_ != 0) {
          setFileTypeValue(other.getFileTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object updateName_ = "";
      /**
       * <code>optional string updateName = 1;</code>
       */
      public java.lang.String getUpdateName() {
        java.lang.Object ref = updateName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updateName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string updateName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateNameBytes() {
        java.lang.Object ref = updateName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updateName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string updateName = 1;</code>
       */
      public Builder setUpdateName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateName = 1;</code>
       */
      public Builder clearUpdateName() {
        
        updateName_ = getDefaultInstance().getUpdateName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateName = 1;</code>
       */
      public Builder setUpdateNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dob_ = "";
      /**
       * <code>optional string dob = 3;</code>
       */
      public java.lang.String getDob() {
        java.lang.Object ref = dob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dob_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dob = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDobBytes() {
        java.lang.Object ref = dob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dob = 3;</code>
       */
      public Builder setDob(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dob = 3;</code>
       */
      public Builder clearDob() {
        
        dob_ = getDefaultInstance().getDob();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dob = 3;</code>
       */
      public Builder setDobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dob_ = value;
        onChanged();
        return this;
      }

      private double salary_ ;
      /**
       * <code>optional double salary = 4;</code>
       */
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>optional double salary = 4;</code>
       */
      public Builder setSalary(double value) {
        
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double salary = 4;</code>
       */
      public Builder clearSalary() {
        
        salary_ = 0D;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional uint32 age = 5;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional uint32 age = 5;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 age = 5;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int fileType_ = 0;
      /**
       * <code>optional .protobuf.eFileType fileType = 6;</code>
       */
      public int getFileTypeValue() {
        return fileType_;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 6;</code>
       */
      public Builder setFileTypeValue(int value) {
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 6;</code>
       */
      public com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType getFileType() {
        com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType result = com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.valueOf(fileType_);
        return result == null ? com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 6;</code>
       */
      public Builder setFileType(com.employeedata.service.app.protobuf.EmployeeDataProto.eFileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fileType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.eFileType fileType = 6;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.UpdatedEmployeeDataMessage)
    }

    // @@protoc_insertion_point(class_scope:protobuf.UpdatedEmployeeDataMessage)
    private static final com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage();
    }

    public static com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdatedEmployeeDataMessage>
        PARSER = new com.google.protobuf.AbstractParser<UpdatedEmployeeDataMessage>() {
      public UpdatedEmployeeDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdatedEmployeeDataMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdatedEmployeeDataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdatedEmployeeDataMessage> getParserForType() {
      return PARSER;
    }

    public com.employeedata.service.app.protobuf.EmployeeDataProto.UpdatedEmployeeDataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_EmployeeDataMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_EmployeeDataMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_UpdatedEmployeeDataMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_UpdatedEmployeeDataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032employeedata_message.proto\022\010protobuf\"t" +
      "\n\023EmployeeDataMessage\022\014\n\004name\030\001 \001(\t\022\013\n\003d" +
      "ob\030\002 \001(\t\022\016\n\006salary\030\003 \001(\001\022\013\n\003age\030\004 \001(\r\022%\n" +
      "\010fileType\030\005 \001(\0162\023.protobuf.eFileType\"\217\001\n" +
      "\032UpdatedEmployeeDataMessage\022\022\n\nupdateNam" +
      "e\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003dob\030\003 \001(\t\022\016\n\006sa" +
      "lary\030\004 \001(\001\022\013\n\003age\030\005 \001(\r\022%\n\010fileType\030\006 \001(" +
      "\0162\023.protobuf.eFileType*\035\n\teFileType\022\007\n\003C" +
      "SV\020\000\022\007\n\003XML\020\001B;\n&com.employeedata.endpoi" +
      "nt.app.protobufB\021EmployeeDataProtob\006prot",
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_EmployeeDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_EmployeeDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_EmployeeDataMessage_descriptor,
        new java.lang.String[] { "Name", "Dob", "Salary", "Age", "FileType", });
    internal_static_protobuf_UpdatedEmployeeDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_UpdatedEmployeeDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_UpdatedEmployeeDataMessage_descriptor,
        new java.lang.String[] { "UpdateName", "Name", "Dob", "Salary", "Age", "FileType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
